### PR TITLE
README: Move from apt-get to pip install

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by Williangalvani** [comment]
I worry that this might not install a requirement outside of pip, like `i2c-tools`

**Comment by patrickelectric** [comment]
wait, do we need i2c-tools for this package ?
Mt only concern that will be installed under --user but almost everybody will use sudo to access the i2c port

**Comment by Williangalvani** [comment]
> wait, do we need i2c-tools for this package ?

apparently: https://packages.debian.org/stretch/python-smbus

**Comment by patrickelectric** [comment]
Ok, we should stay with apt so.

**Pull request closed without merging**
